name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: "${{ matrix.os }}"
    permissions:
      contents: read

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ""

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2

      - name: Install OpenCL dependencies on Linux
        run: sudo apt-get install -y ocl-icd-opencl-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Install OpenCL dependencies on Windows
        run: vcpkg --triplet=x64-windows install opencl
        if: matrix.os == 'windows-latest'

      - run: cargo build --release --target ${{ matrix.target }}
        env:
          LIB: C:\vcpkg\packages\opencl_x64-windows\lib

      - uses: actions/upload-artifact@v4
        with:
          name: yggdrasil-vanity-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/yggdrasil-vanity${{ matrix.suffix }}

  release:
    name: Create Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: yggdrasil-vanity-x86_64-unknown-linux-gnu
          path: ./artifacts/linux

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: yggdrasil-vanity-x86_64-pc-windows-msvc
          path: ./artifacts/windows
      
      - name: Rename artifacts
        run: |
          mv ./artifacts/windows/yggdrasil-vanity.exe ./artifacts/yggdrasil-vanity-x86_64-pc-windows-msvc.exe
          mv ./artifacts/linux/yggdrasil-vanity ./artifacts/yggdrasil-vanity-x86_64-unknown-linux-gnu

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/yggdrasil-vanity-x86_64-pc-windows-msvc.exe
            ./artifacts/yggdrasil-vanity-x86_64-unknown-linux-gnu
